algoritmo "Sucessor e antecessor"
// Disciplina  : [Linguagem e Lógica de Programação]
// Professor   : Bruna
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Luis Felipe Mafort
// Data atual  : 06/03/2025

var

N, S, A: real


inicio

escreva("Digite um número real: ")
leia(N)
S <- N + 1
A <- N - 1
escreva("O sucessor de ", N, " é ", S, " e o antecessor é ", A, ".")

fimalgoritmo